(require 'color-theme)

;; (defun color-theme-bluemidnight()
;;   "Color theme based on the Vim Brookstream theme."
;;   (interactive)
;;   (color-theme-install
;;    `(color-theme-bluemidnight
;;      ((foreground-color . "#bbbbbb")
;;       ,(background)
;;       (cursor-color . "#44ff44")
;;       (background-mode . dark))
;;      (region ((t (:foreground "#000000" :background "#bbbbbb"))))
;;      (highlight ((t (:foreground "#000000" :background "#2f4f4f"))))
;;      (show-paren-match-face ((t (:background "#0d4cbe"))))
;;      (isearch ((t (:bold t :foreground "#000000" :background "Yellow"))))
;;      (lazy-highlight ((t (:foreground "#000000" :background "#bbbbbb"))))
;;      (modeline ((t (:foreground "#ffffff" :background "#2f4f4f"))))
;;      (modeline-inactive ((t (:foreground "#000000" :background "#bbbbbb"))))
;;      (font-lock-builtin-face ((t (:foreground "#4682b4"))))
;;      (font-lock-comment-face ((t (:foreground "#696969"))))
;;      (font-lock-constant-face ((t (:foreground "#00aaaa"))))
;;      (font-lock-function-name-face ((t (:foreground "#1e90ff"))))
;;      (font-lock-keyword-face ((t (:bold t :foreground "#00ffff"))))
;;      (font-lock-preprocessor-face ((t (:foreground "#8470ff"))))
;;      (font-lock-string-face ((t (:foreground "#4682b4"))))
;;      (font-lock-type-face ((t (:foreground "#ffffff"))))
;;      (font-lock-variable-name-face ((t nil)))
;;      (font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff0000")))))))

;; (defun color-theme-bluemidnight ()
;;   "Color theme by Kyle Zentner."
;;   (interactive)
;;   (let
;;     ;; ((color-theme-is-cumulative t))
;;     ;; (color-theme-dark-erc)
;;     ;; (color-theme-dark-gnus)
;;     ;; (color-theme-dark-diff)
;;     ;; (color-theme-dark-eshell)
;;     ;; (color-theme-dark-info)
;;     ;; (color-theme-dark-font-lock)
;;     (color-theme-install
;;      '(color-theme-late-night
;; 	'((background-mode . dark)
;; 	(background-toolbar-color . "#000000")
;; 	(border-color . "#000000")
;; 	(bottom-toolbar-shadow-color . "#000000")
;; 	(cursor-color	. "#808080")
;; 	(foreground-color . "#606060")
;; 	(top-toolbar-shadow-color . "#101010")
;;        (default ((t (nil))))
;;        (bold ((t (:bold t))))
;;        (button ((t (:bold t))))
;;        (custom-button-face ((t (:bold t :foreground "#909090"))))
;;        (fringe ((t (:background "#101010" :foreground "#404040"))))
;;        (header-line ((t (:background "#303030" :foreground "#000000"))))
;;        (highlight ((t (:background "#112a3e" :foreground "#808090"))))
;;        (holiday-face ((t (:background "#000000" :foreground "#707070"))))
;;        (isearch ((t (:foreground "#606060" :background "#224444"))))
;;        (isearch-lazy-highlight-face ((t (:foreground "#112222"))))
;;        (italic ((t (:underline t))))
;;        (menu ((t (:background "#101010" :foreground "#404040"))))
;;        (minibuffer-prompt ((t (:foreground "#505050"))))
;;        (modeline ((t (:background "#101010" :foreground "#404040"))))
;;        (mode-line-inactive ((t (:background "#000000" :foreground "#404040"))))
;;        (modeline-buffer-id ((t (:background "#000000" :foreground "#505050"))))
;;        (modeline-mousable ((t (:background "#000000" :foreground "#505050"))))
;;        (modeline-mousable-minor-mode ((t (:background "#000000" :foreground "#505050"))))
;;        (region ((t (:background "#001315" :foreground "#909090"))))
;;        (primary-selection ((t (:background "#110a3e" :foreground "#808090"))))
;;        (secondary-selection ((t (:background "#111a3e" :foreground "#808090"))))
;;        (ac-selection-face ((t (:background "#111a3e" :foreground "#808090"))))
;;        (ac-candidate-face ((t (:background "#202020" :foreground "#707070"))))
;;        (show-paren-match-face ((t (:foreground "#dddddd"))))
;;        (show-paren-mismatch-face ((t (:foreground "#ff2000"))))
;;        (tool-bar ((t (:background "#101010" :foreground "#707070"))))
;;        (tooltip ((t (:background "#303030" :foreground "#707070"))))
;;        (underline ((t (:bold t))))
;;        (variable-pitch ((t (nil))))
;;        (widget-button-face ((t (:bold t :foreground "#808080"))))
;;        (widget-field-face ((t (:bold t :foreground "#909090")))))))))

(require 'paren)

(defvar transparent-background nil)

(if (display-graphic-p)
    (setq transparent-background "#030405"))

;; (if (display-graphic-p)
;;   (defun background ()
;;         '(background-color . "#030405"))
;;   (defun background ()
;;         ()))

(defun blue-midnight ()
  (interactive)
  (color-theme-install
   `(blue-midnight
      ((background-color . ,transparent-background)
      (background-mode . light)
      (border-color . "#040506")
      (cursor-color . "#acabde")
      (foreground-color . "#556670")
      (mouse-color . "black"))
     (fringe ((t (:background "#040506"))))
     (mode-line ((t (:foreground "#6a7a90" :background "#080f12"))))
     (region ((t (:background "#181d21"))))
     (secondary-selection ((t (:background "#111a3e" :foreground "#808090"))))
     (ac-selection-face ((t (:background "#111a3e" :foreground "#808090"))))
     (ac-candidate-face ((t (:background "#202020" :foreground "#707070"))))
     (font-lock-builtin-face ((t (:foreground "#7bd5c0"))))
     (font-lock-comment-face ((t (:foreground "#1e4b66"))))
     (font-lock-function-name-face ((t (:foreground "#0083ed"))))
     (font-lock-keyword-face ((t (:foreground "#10c0e0"))))
     (font-lock-string-face ((t (:foreground "#0681b7"))))
     (font-lock-type-face ((t (:foreground"#2a07f2"))))
     (font-lock-constant-face ((t (:foreground "#730fe6"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#537293" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     (show-paren-match-face ((t (:foreground "#ecebfe" :bold t :background ,transparent-background))))
     (show-paren-mismatch-face ((t (:foreground "#ff2000"))))
     (highlight ((t (:background "#112a3e" :foreground "#808090"))))
     (holiday-face ((t (:background "#000000" :foreground "#707070"))))
     (isearch ((t (:foreground "#b0b0f0" :background "#224444"))))
     (isearch-lazy-highlight-face ((t (:foreground "#112222"))))
     (underline ((t (:bold t))))
     (widget-field ((t (:background "gray5" :foreground "white smoke"))))
     )))

(provide 'blue-midnight)

(color-theme-initialize)
(blue-midnight)
;; (color-theme-bluemidnight)
